sudo: false
notifications:
  email: false
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3
      - cabal-install-1.22
before_install:
  - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$HOME/.cabal/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
install:
  cabal install --only-dependencies --enable-tests
script:
  - cabal configure --enable-tests && cabal build && cabal test --show-details=streaming
